from sentence_check import *

#answer needs to be same structure. (subj subj, verb, verb)
print (compare_sentences("Did the not green penguin eat", "The really green penguin ate."))
print (compare_sentences("Is it true that the not cute penguin runs fast", "The cute penguin runs fast"))
print (compare_sentences("Is it true that the young penguins are really cute?", "All little birds are really cute"))
print (compare_sentences("Do some penguins read books about sports daily?", "Every animal in the northern hemisphere reads books about sports daily."))
print (compare_sentences("Does the yellow flute make on the table the music", "The blue flute creates on the table the sound."))
print (compare_sentences("Is it true that he finds penguins", "Penguins find him."))
print (compare_sentences("Is it true that humans climb trees?", "Every man has climbed a tree before.")) # dictionary size error ?
print (compare_sentences("Is it true that bears from the forest eat?", "The bears from the forest eat honey."))
print (compare_sentences("Did the primary students finish their homework?", "Only the secondary students completed their assignments."))
print (compare_sentences("Is it true that the hare always runs quick?", "The hare never runs slow."))

#test sentences
print (compare_sentences("Did the automobile get stopped by the police today?", "The car with the blinkers got stopped today."))
print (compare_sentences("Is it true that the girl’s favorite show is on the Discovery channel?", "Her favorite channel is the Disney channel."))
print (compare_sentences("Is it true that the your favorite type of chocolate is not dark chocolate?", "My favorite type of chocolate is milk chocolate with caramel."))
print (compare_sentences("Does the alarm never go off?", "The emergency alarm went off this morning."))
print (compare_sentences("Is it true that the lady’s clothing is very beautiful?", "The girl’s dress is really pretty."))
print (compare_sentences("Is it true that the warm weather makes her sad?", "She’s very glad the weather is warm."))
print (compare_sentences("Does the pupil use many hyphenations in her writing?", "The student uses a lot of hyphenation in her essays."))
print (compare_sentences("Did some people go to the event in the city?", "Everyone went to the mixer in Boston today."))
print (compare_sentences("Is it true that the winners of the competition did not receive a trophy?", "The prize for the competition was a trophy."))
print (compare_sentences("Does the boss give promotions to the employees yesterday?", "His boss gave him a promotion today."))
print (compare_sentences("Is is true that his interests are in sports?", "The hobby of the agent is football."))
print (compare_sentences("Did the coach tell your grandmother to exercise?", "A coach told my granny to visit the new room."))
print (compare_sentences("Have his organs been making sounds?", "His intestines make sound when he is hungry."))
print (compare_sentences("Does the obligation of the student depend on the teacher?", "The obligation of the teacher depends on the student."))
print (compare_sentences("Do all insecure banks not ask for passwords?", "Every secure bank account asks for a password."))
print (compare_sentences("Did the wasp sting the boy on the arm?", "Yesterday the wasp stung the boy on the nose."))
print (compare_sentences("Does every animal roll?", "Some armadillos rolls around on the grass."))
print (compare_sentences("Does the worker always put tiles together?", "A house builder sometimes lays tiles on the floor."))
print (compare_sentences("Will the parade leader trip on the wire?", "The leader of the parade tripped on the wire for the microphone."))
